version: 2
updates:
- package-ecosystem: pip
  directory: "/app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.63
    - 1.17.0
    - 1.17.1
    - 1.17.10
    - 1.17.11
    - 1.17.12
    - 1.17.13
    - 1.17.14
    - 1.17.15
    - 1.17.16
    - 1.17.17
    - 1.17.18
    - 1.17.19
    - 1.17.2
    - 1.17.20
    - 1.17.21
    - 1.17.22
    - 1.17.23
    - 1.17.24
    - 1.17.25
    - 1.17.26
    - 1.17.27
    - 1.17.28
    - 1.17.29
    - 1.17.3
    - 1.17.30
    - 1.17.32
    - 1.17.33
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.38
    - 1.17.39
    - 1.17.4
    - 1.17.40
    - 1.17.41
    - 1.17.43
    - 1.17.44
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.48
    - 1.17.49
    - 1.17.5
    - 1.17.50
    - 1.17.51
    - 1.17.52
    - 1.17.53
    - 1.17.54
    - 1.17.55
    - 1.17.56
    - 1.17.57
    - 1.17.58
    - 1.17.59
    - 1.17.6
    - 1.17.7
    - 1.17.8
    - 1.17.9
  - dependency-name: faker
    versions:
    - 6.4.1
    - 6.5.0
    - 6.5.2
    - 6.6.0
    - 6.6.1
    - 6.6.2
    - 6.6.3
    - 7.0.1
    - 8.0.0
    - 8.1.0
  - dependency-name: wagtail
    versions:
    - 2.12.2
    - 2.12.3
    - 2.12.4
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: pytest
    versions:
    - 6.2.2
    - 6.2.3
  - dependency-name: django
    versions:
    - 3.1.6
  - dependency-name: wagtail-nhsuk-frontend
    versions:
    - 0.5.0
    - 0.7.0
  - dependency-name: ipdb
    versions:
    - 0.13.5
    - 0.13.6
    - 0.13.7
  - dependency-name: wagtail-cache
    versions:
    - 1.0.1
    - 1.0.2
  - dependency-name: rollbar
    versions:
    - 0.15.2
  - dependency-name: django-autocomplete-light
    versions:
    - 3.8.1
    - 3.8.2
  - dependency-name: coverage
    versions:
    - "5.5"
  - dependency-name: factory-boy
    versions:
    - 3.2.0
