services:
  # Postgres
  db:
    image: postgres:10-alpine
    restart: always
    env_file:
      - docker-compose.env
    volumes:
      - ./docker/db/data/:/var/lib/postgresql/data

  # Redis
  redis:
    restart: always
    image: sameersbn/redis:latest
    env_file:
      - docker-compose.env
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/var/lib/redis

  # Application
  web:
    image: nhsx:latest
    environment:
      - ENVKEY=${ENVKEY}
    env_file:
      - docker-compose.env
    restart: always
    build:
      context: ./
      target: dev
      dockerfile: ./docker/web/Dockerfile
      args:
        - SERVER_ENV=development
        - ENVKEY=${ENVKEY}
    volumes:
      - ./app/:/usr/srv/app:Z
      - ./app/media:/usr/srv/app/media:Z

    ports:
      - "5000:5000"
      - "8000:8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
